### ISSUE TITLE
[BUG] Replace 2 incorrect EncryptionMethod algorithms in generateServiceProviderMetadata

### ISSUE THREAD

**Issue by alexstuart** [node-saml/node-saml#13]
When generating SP metadata, [saml.ts](https://github.com/node-saml/node-saml/blob/01b3254eb6f46ac65ee275b06ab89de27132b15a/src/saml.ts#L1400) outputs 4 EncryptionMethod elements:

```
          EncryptionMethod: [
            // this should be the set that the xmlenc library supports
            { "@Algorithm": "http://www.w3.org/2001/04/xmlenc#aes256-gcm" },
            { "@Algorithm": "http://www.w3.org/2001/04/xmlenc#aes128-gcm" },
            { "@Algorithm": "http://www.w3.org/2001/04/xmlenc#aes256-cbc" },
            { "@Algorithm": "http://www.w3.org/2001/04/xmlenc#aes128-cbc" },
          ],
```

However the two elements that are intended to specify AES with GCM are invalid.

The algorithms should be http://www.w3.org/2009/xmlenc11#aes256-gcm and http://www.w3.org/2009/xmlenc11#aes128-gcm respectively, as described in [XML Encryption Syntax and Processing Version 1.1](https://www.w3.org/TR/xmlenc-core1/#sec-AES-GCM)

**Comment by cjbarth** [comment]
I appreciate your identifying this. It would be nice if we could release it as a patch on the 3.x branch at `passport-saml` too.

**Comment by tomgiddingsjisc** [comment]
I've created a PR for the change here, and will do so for the 3.x branch on `passport-saml` tomorrow.

**Comment by tomgiddingsjisc** [comment]
Thanks for merging this so quickly @cjbarth! I've created a PR for the 3.x branch as requested.

**Comment by cjbarth** [comment]
Thank you for creating PRs. [v3.1.1](https://github.com/node-saml/passport-saml/releases/tag/v3.1.1) of passport-saml has been released.
