### ISSUE TITLE
[ENHANCE] v4.0.0-beta.2 tag missing on github but published as latest on NPM

### ISSUE THREAD

**Issue by busla** [node-saml/node-saml#144]
FYI: Just noticed that v4.0.0-beta.2 is the latest release on NPM but missing on Github.

Available tags:
v4.0.0-beta.3
missing
v4.0.0-beta.1

**Comment by cjbarth** [comment]
Did you try @node-saml/node-saml from NPM?

**Comment by busla** [comment]
No, and installing works fine.

Just pointing out that the published version doesnt exist as a git tag in this repository.

I usually run quickly through the source code on Github before using new libraries and noticed this when searching for 4.0.0-beta.2.

**Comment by barryhagan** [comment]
fwiw, version 4.0.0-beta.2 is https://github.com/node-saml/node-saml/commit/97d580725b69c7e27e41deb9e925b8cbfe0945e8

**Comment by cjbarth** [comment]
This has been tagged.
