### ISSUE TITLE
[BUG] Regression: "SAML assertion AudienceRestriction has no Audience value"

### ISSUE THREAD

**Issue by gugu** [node-saml/node-saml#155]
After upgrading to beta 3 I get this error: "SAML assertion AudienceRestriction has no Audience value". I don't have assertion in my logs, unfortunately I don't have assertion available to debug

**To Reproduce**

The only information I have for now is that the client uses OneLogin. The code is:

const { profile } = await saml.validatePostResponseAsync(req.body);

**Expected behavior**
It should work as before

**Environment**

- Node.js version: 16
- node-saml version: 4.0.0-beta.3

**Comment by markstos** [comment]
What was the fix?

**Comment by gugu** [comment]
It was me not reading changelog. I did not have audience parameter and defauld behaviour was changed
