### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by sarathmaf** [node-saml/node-saml#16]
This library is very handy and will be useful for any custom saml integrations that any application wants to do.
But what is blocking the teams from using the library is the lack of @types/node-saml.

So is there any plan to add @types support?

**Comment by cjbarth** [comment]
node-saml is written in TypeScript, so the types are built-in.

**Comment by sarathmaf** [comment]
When you do an npm install, you get the code in javascript. You cannot use the library in a typescript project if we just do 

`import { SAML } from 'node-saml';`

You will get a type deceleration missing error.

```
`Could not find a declaration file for module 'node-saml'. '/node_modules/node-saml/src/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/node-saml` if it exists or add a new declaration (.d.ts) file containing `declare module 'node-saml';`ts(7016)`
```
So either it has to be added manually or with `npm i --save-dev @types/node-saml`.

That is what I meant by adding @types support.

**Comment by gugu** [comment]
I think you need to enable definitions in tsconfig.json

**Comment by sarathmaf** [comment]
@cjbarth @gugu Without the type definition, we cannot use this lib in any Typescript project. Either it has to be preset via https://github.com/DefinitelyTyped/DefinitelyTyped so a user can install it like `npm i --save-dev @types/node-saml` or anyone who use this library has to create their own type definition.

**Comment by gugu** [comment]
I mean, module authors need to enable it

**Comment by cjbarth** [comment]
What version of `node-saml` are you using? If you look at the head of `passport-saml`, it is working with Types just fine from the `node-saml` project.

**Comment by gugu** [comment]
@sarathmaf  `npm install https://github.com/node-saml/node-saml`

**Comment by sarathmaf** [comment]
@gugu  Yes, this will fix the problem. if we install directly from npm. I was doing `npm i node-saml`
