### ISSUE TITLE
[ENHANCE] getLogoutResponseUrlAsync should be exposed

### ISSUE THREAD

**Issue by Marsup** [node-saml/node-saml#193]
**Is your feature request related to a problem? Please describe.**
I see that getLogoutResponseUrl is just a wrapper around getLogoutResponseUrlAsync, so my question is simply why is that last method not public? This forces users to re-wrap that call into a promise when used in an async/await context.

**Describe the solution you'd like**
Change from protected to public.

**Describe alternatives you've considered**
I'm not sure there's a need for alternatives.

**Comment by cjbarth** [comment]
Would you be willing to put up a PR for this?

**Comment by Marsup** [comment]
Sure thing. Should I add tests or do you consider it tested through getLogoutResponseUrl?

**Comment by cjbarth** [comment]
I would add a test so we make sure that the public contract is stable.
