### ISSUE TITLE
Followup discussion from passport-saml PR

### ISSUE THREAD

**Issue by kriss1897** [node-saml/node-saml#2]
PR: https://github.com/node-saml/passport-saml/pull/574

**Comment by cjbarth** [comment]
The [node-saml](https://github.com/node-saml/node-saml) and [passport-saml](https://github.com/node-saml/passport-saml) projects are accepting all PRs that actually complete the separateion of the Node-SAML stuff from the Passport stuff. We wish to make a pair of 4.0.0 releases that complete this separation and where [node-saml](https://github.com/node-saml/node-saml) is a dependency of [passport-saml](https://github.com/node-saml/passport-saml).

**Comment by kriss1897** [comment]
@zoellner @cjbarth Guys, who will be able to review the PRs? https://github.com/node-saml/passport-saml/pull/593 and https://github.com/node-saml/node-saml/pull/5
