### ISSUE TITLE
[BUG] Parameter cert should be optional

### ISSUE THREAD

**Issue by nejcokorn** [node-saml/node-saml#241]
The protocol does not require SAML Request/Response messages to be signed.

Therefore I don't see any reason why the parameter **cert** would be required.
If I am correct it was not required in the earlier version of this package.

I get the following error message when I leave out the **cert** parameter
```
TypeError: cert is required
    at assertRequired (/node_modules/@node-saml/node-saml/lib/utility.js:7:15)
    at SAML.initialize (/node_modules/@node-saml/node-saml/lib/saml.js:33:38)
    at new SAML (/node_modules/@node-saml/node-saml/lib/saml.js:24:29)
    at new AbstractStrategy (/node_modules/@node-saml/passport-saml/lib/strategy.js:28:26)
    at new Strategy (/node_modules/@node-saml/passport-saml/lib/strategy.js:215:1)
```

**Environment**

- Node.js version: 16.19.0
- @node-saml/node-saml version: 4.0.2

**Comment by aykutbulca** [comment]
@srd90 You are absolutely right about authentication response validation, but the IdP's certificate is not needed for some other functionalities, i.e., `generateServiceProviderMetadata`. Should it not be required for some actions rather than the whole library?

**Comment by cjbarth** [comment]
@aykutbulca , you are correct in your statement, but what do you propose as a solution (please open a discussion on this matter instead of continuing here in this closed item).

**Comment by markstos** [comment]
@srd90 Thanks for your reply here!

**Comment by aykutbulca** [comment]
@cjbarth, sorry that I missed this comment. I'll start a new discussion around that; thanks!
