### ISSUE TITLE
[ENHANCE] Make AuthnRequestsSigned=true decidable by a config parameter

### ISSUE THREAD

**Issue by aykutbulca** [node-saml/node-saml#243]
I've been working on migrating a project with an older version of `passport-saml` to the latest version of `node-saml` package, and one of the behavior changes made me think that there might be something we could add to the `node-saml` library as an enhancement.

Currently, if `generateServiceProviderMetadata` method is called with a SAML config containing `options.privateKey`, it adds the "signing" key descriptor to the metadata with the attribute `AuthnRequestsSigned="true"`. When I checked the SAML spec [here](https://www.oasis-open.org/committees/download.php/56785/sstc-saml-metadata-errata-2.0-wd-05.pdf), it mentions `AuthnRequestsSigned` in SP descriptor as follows:

> AuthnRequestsSigned [Optional]
>
> Optional attribute that indicates whether the <samlp:AuthnRequest> messages sent by this
> service provider will be signed. If omitted, the value is assumed to be false. [E7]A value of
> false (or omission of this attribute) does not imply that the service provider will never sign its
> requests or that a signed request should be considered an error. However, an identity provider
> that receives an unsigned <samlp:AuthnRequest> message from a service provider whose
> metadata contains this attribute with a value of true MUST return a SAML error response and
> MUST NOT fulfill the request.

- If `AuthnRequestsSigned="true"`, it means that SPs will **always** sign the authn requests; otherwise, identity providers must reject it.
- If `AuthnRequestsSigned="false"` or omitted, it means that SPs _might_ sign the authn requests occasionally.

So, my understanding of this is that if an SP signs its requests from time to time (depending on a condition, maybe), it should provide its metadata with the "signing" key and with the attribute `AuthnRequestsSigned="false"` (so that idPs don't reject the requests without signature). However, it is not possible to do this with the existing `node-saml` library (v4.0.3) since having a signing cert in the`generateServiceProviderMetadata` automatically adds `AuthnRequestsSigned` as `true`.

I think the decision about the `AuthnRequestsSigned="true"` attribute in metadata could be made by a new config option instead of adding it as `true` whenever the `options.privateKey` is provided. What do you think? If that makes sense, I'm happy to provide a PR for it.

**Comment by cjbarth** [comment]
I appreciate your research here, but I'm honestly struggling to understand a real-world use-case where the SP would want to be able sign a request, but choose not to. I also don't understand how `node-saml`, or any SP for that matter, might choose to sign or not sign. If you can sign, why wouldn't you? And, if you sign, why wouldn't you want that signature checked by the IdP?

If you are trying to talk to several different IdPs, then I would expect that you'd have a different config for each, using a `MultiSamlConfig` for example, and then you could still pick if you wanted to sign or not.

**Comment by aykutbulca** [comment]
I can't think of a real-world use case that strictly needs this, either. 

The issue we had was that it created a mismatch between the metadata we provide (the library automatically added `AuthnRequestsSigned="true"`) and the SAML Authn Requests that we send to IdPs (since we were not signing the requests). We decided to sign the requests (as you said, why should we not), which cleared the mismatch.

I checked the SAML spec because I wanted to ensure we don't break anything (what if we have customers whose IdPs can not handle the signatures, and what if we don't comply with the spec completely). That is when I started thinking that even if we can't think of a real-world scenario, (according to spec) it is not 100% correct to add `AuthnRequestsSigned="true"` to the metadata depending on the existence of a signing certificate. 

The `node-saml` library can continue to work as it is right now (to be secure by default), but it can also provide a config flag to override the `AuthnRequestsSigned=true` decision to comply with the spec.

**Comment by cjbarth** [comment]
It actually seems more correct (secure) to make sure that `node-saml` is signing whenever it has a way to do so (i.e. `AuthnRequestsSigned="true"` is set). I'd welcome a PR that does that. I appreciate the flexibility the spec provides, but without a needed use-case, I don't see a need to invest in it. What seems a higher priority is to avoid the problem you experienced. Would you be up for creating a PR of that nature?

**Comment by aykutbulca** [comment]
> It actually seems more correct (secure) to make sure that node-saml is signing whenever it has a way to do so (i.e. AuthnRequestsSigned="true" is set). 

Actually, this is how `node-saml` works right now. Signing a request and adding the `AuthnRequestsSigned="true"` attribute to the metadata are both decided with the same condition (existence of the `options.privateKey`). 

What `node-saml` is not doing is that if you have the `options.privateKey`, you cannot change the value of `AuthnRequestsSigned` to `false` — which is valid according to spec. If an SP wants to share their signing key in their metadata, they must sign their requests, `node-saml` provides no other option.

Your concerns are valid; I just wanted to share this if we can make an enhancement to the library so that SPs can also decide between the following metadata alternatives:

- Signing key + (AuthnRequestsSigned = true) => can be done if privateKey is provided
- **Signing key + (AuthnRequestsSigned = false) => valid according to spec but cannot be done, see [here](https://github.com/node-saml/node-saml/blob/master/src/metadata.ts#L73)**
- No Signing key + (AuthnRequestsSigned = true) => not a valid case
- No Signing key + (AuthnRequestsSigned = false) => can be done if privateKey is not provided

I understand if you don't want to invest in it. If so, we can close the issue.

**Comment by cjbarth** [comment]
Since what we are doing is the most secure option and there is no identified use-case for the proposal, I feel that we should just close this issue until someone identifies a need. Does that seem reasonable to you @aykutbulca ?

**Comment by aykutbulca** [comment]
Yes, that makes sense @cjbarth. 

If someone needs it, they can simply replace the `AuthnRequestsSigned="true"` attribute with an empty string from the returned metadata XML by `generateServiceProviderMetadata` (as a workaround).
