### ISSUE TITLE
[ENHANCE] Examples using node-saml

### ISSUE THREAD

**Issue by r0oto0r** [node-saml/node-saml#258]
Hey devs,

sorry for opening an issue, but I wasn't able to ask a question in discussions. I just wanted to know if there are some public examples using this library?

Cheers,
Ben

**Comment by r0oto0r** [comment]
Hey @srd90 and thanks for the detailed answer! I do really appreciate it.

I was looking into creating my own IDP with node-saml but as you've already mentioned, samlify seems to be the better fit for this task. So, I've moved away from node-saml in favor of samilfy and so far it's working great!

Thanks for your time and sorry for being not specific enough in the first place.

Cheers,
Ben

**Comment by alifarooq-zk** [comment]
> Hey @srd90 and thanks for the detailed answer! I do really appreciate it.
> 
> I was looking into creating my own IDP with node-saml but as you've already mentioned, samlify seems to be the better fit for this task. So, I've moved away from node-saml in favor of samilfy and so far it's working great!
> 
> Thanks for your time and sorry for being not specific enough in the first place.
> 
> Cheers, Ben

Hi, were you able to implement your own IdP using Samlify. You could share your repo or any guide on how you accomplished it, that would be great. Thanks.

**Comment by markstos** [comment]
I'll look at the permissions issue. 

Another option for SAML IdP software is Zitadel, which runs as a container.

**Comment by alifarooq-zk** [comment]
> @alifarooq-zk since you did not list any festures that you expect from IdP you must be after some as general purpose IdP as possible (which is huge effort). Here are some open source alternatives:
> 
> * https://www.keycloak.org
>   
>   * https://github.com/keycloak/keycloak
> * https://shibboleth.atlassian.net/wiki/spaces/IDP5/overview
>   
>   * https://git.shibboleth.net/view/?p=java-identity-provider.git;a=tree;h=refs/heads/main;hb=refs/heads/main
> * https://simplesamlphp.org
>   
>   * https://github.com/simplesamlphp/simplesamlphp
> 
> Aforementioned list with links to codebases was provided just as a reference to "visualize" the scope/magnitude of your request from development effort point of view. List must not be interpreted as "recommended IdP solutions list". You know your specific requirements for your IdP and you may use your requirement list to evaluate some of aforementioned or any other ( https://en.wikipedia.org/wiki/SAML-based_products_and_services ).
> 
> If you choose to implement your IdP by yourself pay attention to discovered vulnerabilities of other products and try to avoid similar issues. Here are few examples:
> 
> * https://nvd.nist.gov/vuln/search/results?form_type=Basic&results_type=overview&query=keycloak&search_type=all&isCpeNameSearch=false
> * https://shibboleth.atlassian.net/wiki/spaces/IDP5/pages/3199512795
> * https://nvd.nist.gov/vuln/search/results?isCpeNameSearch=false&query=simplesamlphp&results_type=overview&form_type=Basic&search_type=all&startIndex=20
> * https://simplesamlphp.org/security/
> 
> Aforementioned links were provided just as a reference of (security) issues that other projects has had while implementing more or less "general purpose IdP".
> 
> Here are few resources to use as a reference while implementing IdP. Note that these do not discuss IdP product specific capabilities like possibilities to integrate with e.g. any enterprise directory services to perform user lookups etc.
> 
> 1. Security Assertion Markup Language (SAML) V2.0 Technical Overview. Committee Draft 02, 25 March 2008
>    https://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-tech-overview-2.0-cd-02.pdf
> 2. Assertions and Protocols for the OASIS Security Assertion Markup Language (SAML) V2.0 OASIS Standard, 15 March 2005
>    https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf
> 3. Profiles for the OASIS Security Assertion Markup Language (SAML) V2.0 OASIS Standard, 15 March 2005
>    https://docs.oasis-open.org/security/saml/v2.0/saml-profiles-2.0-os.pdf
> 4. Security and Privacy Considerations for the OASIS Security Assertion Markup Language (SAML) V2.0 OASIS Standard, 15 March 2005
>    https://docs.oasis-open.org/security/saml/v2.0/saml-sec-consider-2.0-os.pdf
> 5. Metadata for the OASIS Security Assertion Markup Language (SAML) 2.0 OASIS Standard, 15 March 2005
>    https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf
> 6. and this: https://cheatsheetseries.owasp.org/cheatsheets/SAML_Security_Cheat_Sheet.html
> 
> PS. Constructing and consuming SAML protocol messages to/from the transport layer is very small part of whole effort of implementing even very basic production grade IdP with e.g. Web SSO and SLO profiles support.

Thanks for detailed reply. But I'm looking for something very specific. The scenario is that we have a Strapi backend that provide simple rest api to a frontend for various resources. It have many users, i want this backend to act as IdP for Coursera so that users of this app can access Coursera without having to sign up on Coursera. We cant use some other IdP, we want to auth the users ourselves i.e. take saml requests and generate saml response. Any advice or guidance will be appreciated. Thanks again.

**Comment by markstos** [comment]
> Please notice the timestamp of message which discussed permission issue. 

@srd90 Ha, that's what I get for reading this on my phone. I guess I'm never surprised when something has managed to break anymore that I thought was working.  I'm curious if you happened to check out Zitadel. I like that the product runs in a single container, only requiring PostgreSQL as an additional dependency. My initial attempts to make a SAML connection between it and passport-saml have gone smoothly.
