### ISSUE TITLE
Remove unmaintained `should.js`

### ISSUE THREAD

**Issue by cjbarth** [node-saml/node-saml#26]
[should.js](https://github.com/shouldjs/should.js) is unmaintained and should be removed from `node-saml`.

**Comment by kg0r0** [comment]
I opened PR https://github.com/node-saml/node-saml/pull/41.
I've replaced should.js with [chai](https://www.npmjs.com/package/chai), but if there is a library I should use, please let me know. I will rewrite the tests using the specified library.

**Comment by markstos** [comment]
I use `chai` for another project and it seems to work fine-- complete and well-documented.
