### ISSUE TITLE
[ENHANCE] cacheProvider type should be an interface

### ISSUE THREAD

**Issue by barryhagan** [node-saml/node-saml#28]
**Is your feature request related to a problem? Please describe.**

If you want to implement your own `cacheProvider` the type must match the included in-memory `CacheProvider` class.  This includes internals of the class (`cacheKeys` and `options`) since those are not marked private.

**Describe the solution you'd like**

export an interface for `cacheProvider` rather than the concrete in-memory implementation.

**Describe alternatives you've considered**

stubbing out the props necessary for TypeScript to not complain.

**Comment by cjbarth** [comment]
Are you interested in creating a PR for one of these options?
