### ISSUE TITLE
[BUG] SAML LogoutResponse InResponseTo validation is not working

### ISSUE THREAD

**Issue by eerohakio** [node-saml/node-saml#331]
Correct me if I'm wrong but it seems that SAML LogoutResponse InResponseTo validation is not working.

When going through code this one was particularly interesting https://github.com/node-saml/node-saml/blob/master/src/saml.ts#L698

It seems that InResponseTo is always taken from Response rather than LogoutResponse when request is LogoutResponse type.
All the test cases/static mocks are made with only Response format without any tests to test LogoutResponse validations.

Is there a way to overcome this issue with LogoutResponses?

Example from SAML official bindings
```
<samlp:LogoutResponse xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
xmlns="urn:oasis:names:tc:SAML:2.0:assertion"
 ID="b0730d21b628110d8b7e004005b13a2b"
InResponseTo="d2b7c388cec36fa7c39c28fd298644a8"
 IssueInstant="2004-01-21T19:00:49Z" Version="2.0">
 <Issuer>https://ServiceProvider.com/SAML</Issuer>
 <samlp:Status>
 <samlp:StatusCode
Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
 </samlp:Status>
</samlp:LogoutResponse>
```

**Comment by eerohakio** [comment]
Thanks for your reply!
This explains part of our issue which means I need to investigate codebase more. Also have to investigate if it’s possible to use HTTP-Redirect binding instead which could solve the issue.

**Comment by cjbarth** [comment]
@eerohakio , if this issue no longer applies, feel free to close it.
