### ISSUE TITLE
Generate SP metadata without knowing IdP cert

### ISSUE THREAD

**Issue by nwalters512** [node-saml/node-saml#336]
**Is your feature request related to a problem? Please describe.**

I use the `MultiSamlStrategy` Passport strategy. I'd like to provide metadata URLs to our IdPs, which I can build with `MultiSamlStrategy#generateServiceProviderMetadata`.

This works fine if I know the IdP's cert and can have `getSamlOptions` return an option object with `cert`. However, during initial setup, I may not immediately know the IdP's certificate. I should still be able to generate metadata for them, as (as far as I know) that metadata doesn't depend on their own certificate. However, if `getSamlOptions` returns `cert: null` (because I don't yet know it), the following assertion fails:

https://github.com/node-saml/node-saml/blob/e691ccf39b9f3521268fc31b8b8f099beae4654c/src/saml.ts#L98

**Describe the solution you'd like**

Since the XML metadata doesn't depend on the IdP's cert, I'd like to be able to generate it before I do in fact know their cert.

**Describe alternatives you've considered**

When someone asks for our metadata URL, I can of course say "no, _you_ give me your metadata URL first so I can get your cert". However, it would be very nice to be able to always provide it first.

**Comment by cjbarth** [comment]
Just at first glance, i believe this is supposed to be your public cert. Otherwise, I agree with you that you should be able to generate metadata without anything from the IdP.

**Comment by nwalters512** [comment]
@cjbarth The `node-saml` docs state that this should be the IdP's public cert:

> `cert`: the IDP's public signing certificate used to validate the signatures of the incoming SAML Responses

@srd90 thank you for the link to that discussion, I'm very much in agreement that having a certificate configured is critical for security and I'm not trying to question that.

It didn't occur to me that I could provide _any_ string for the cert, but yes, given that the constructor currently only validates that it's a string and not that it's a well-formed and valid certification, that should be safe. I'd be a little worried about future changes that move such validation to the constructor. If such a change is ever considered, this is a use case that should be considered with it.

Using `generateServiceProviderMetadata` is also a good idea, since it seems like that takes an object that basically matches what `getSamlOptions` will return. However, that doesn't appear to be a public API (it's not exported from `src/index.ts`. @cjbarth, do you think you or another maintainer would accept a PR that officially makes `generateServiceProviderMetadata` part of the API?

**Comment by cjbarth** [comment]
I have no objection to a PR that makes `metadata/generateServiceProviderMetadata()` part of the API as long as there is a test for it.
