### ISSUE TITLE
[BUG] Potential bypass for `InResponseTo` Assertion Validation

### ISSUE THREAD

**Issue by cjbarth** [node-saml/node-saml#82]
#43 introduced a bug whereby an attacker would modify a SAML document to effectively disable checking of assertion valid date/time ranges.

See https://github.com/node-saml/node-saml/pull/43#issuecomment-1118007252 for more information.

**Comment by cjbarth** [comment]
@afurlane Are you available to work on this, or should we roll-back the bug-inducing PR until you get some time?

**Comment by afurlane** [comment]
@cjbarth, sorry for being late. I'm working on the code, reading and re-reading the specs. I think I should be opening a pull-request soon.

**Comment by afurlane** [comment]
@cjbarth I'm struggling with this trouble. If you could take a look, search for "valid xml document with multiple SubjectConfirmation should fail if no one is valid" in tests.spec.ts. Well, it is the same test in "valid xml document with multiple SubjectConfirmation should validate, first is expired so it should take the second one" and the assert reject checks for two differente messages. https://github.com/afurlane/node-saml/tree/bypass_for_inresponseto

**Comment by afurlane** [comment]
@cjbarth, I found that:

`        await assert.rejects(samlObj.validatePostResponseAsync(container), (err) => {
          assert.strictEqual(err.message, 
            "No valid subject confirmation found among those available in the SAML assertion")
        });
`

Will work as expected. The test fails because of:
`1) node-saml /
       saml.js / 
         validatePostResponse checks /
           valid xml document with multiple SubjectConfirmation should fail if no one is valid:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'InResponseTo does not match subjectInResponseTo'
- 'No valid subject confirmation found among those available in the SAML assertion'
      + expected - actual

      -InResponseTo does not match subjectInResponseTo
      +No valid subject confirmation found among those available in the SAML assertion`

Ok, so I think I need to fix the code and the tests too.

**Comment by cjbarth** [comment]
Address by #87
