### ISSUE TITLE
[ENHANCE] Public getSAMLRequestValue method

### ISSUE THREAD

**Issue by alex-way** [node-saml/node-saml#94]
**Is your feature request related to a problem? Please describe.**

I'm using node-saml as part of my `Remix` web stack. However, I don't want to directly use the `getAuthorizeFormAsync` as it means I can't customise the form at all and just generally makes working with the library more difficult then I feel it needs to be.

**Describe the solution you'd like**

A getSAMLRequestValue (or similarly named) method on the main `SAML` class that I can use to generate the Base64 encoded SAMLRequest value, to pass into my own form.

**Describe alternatives you've considered**

I'm doing the following as a workaround currently which works but isn't ideal:
```ts
 const authForm = await saml.getAuthorizeFormAsync("");
  // Extract the SAMLRequest value with regex
  const SAMLRequestValue = authForm
    .split(`name="SAMLRequest" value="`)[1]
    .split(`"`)[0];
```

I would love to contribute to the library and if I can I'll get a PR raised to propose a solution.

**Comment by alex-way** [comment]
Looks like there's already a method which does exactly that, but it's private: `generateAuthorizeRequestAsync`

**Comment by cjbarth** [comment]
The `node-saml` library was broken off from `passport-saml` for just this reason, so we're open to a PR to make this functionality public if there is a use-case (which it seems there is). One word of caution: there is a significant portion of that function that isn't covered by tests (https://app.codecov.io/gh/node-saml/node-saml/blob/master/src/saml.ts). If you're going to use that function, you might want to write some tests to ensure that its functionality doesn't change on you once it goes public (or if it does, it can be clearly called out in the PR; it is beta after all).

**Comment by alex-way** [comment]
> The `node-saml` library was broken off from `passport-saml` for just this reason, so we're open to a PR to make this functionality public if there is a use-case (which it seems there is). One word of caution: there is a significant portion of that function that isn't covered by tests (https://app.codecov.io/gh/node-saml/node-saml/blob/master/src/saml.ts). If you're going to use that function, you might want to write some tests to ensure that its functionality doesn't change on you once it goes public (or if it does, it can be clearly called out in the PR; it is beta after all).

Thanks Chris, I think I'll be able to get an implementation in place. The testing is another matter but I'll certainly try my best!
